### ISSUE TITLE
Error: issue modification while signing

### ISSUE THREAD

**Issue by a1991car** [fidlabs/allocator-tooling#114]
Related pages:
https://github.com/a1991car/Allocator-Public-Data/issues/26
https://allocator.tech/application/a1991car/Allocator-Public-Data/f1pse3d6xvjch3pfk5lvgjmo6w6gyye4ig5eeseri

When I was signing, coincidentally, the applicant modified the request at the same time. As a result, the DataCap has been allocate, but the status has not been synchronized to the web page correctly.

**Comment by kacperzuk-neti** [comment]
Thanks for report, please don't take any actions on this application until this is resolved. We're looking into it.

**Comment by Wennegit** [comment]
It shows here that the client cannot be found. Should we wait for it to be repaired or reapply?
<img width="797" alt="Image" src="https://github.com/user-attachments/assets/aeabbd97-283f-4759-8215-7a9a5749871b" />

**Comment by a1991car** [comment]
It seems that the robot has not entered this client. @kacperzuk-neti Can you help us restore the data to normal first? We need it now.

**Comment by kacperzuk-neti** [comment]
> It seems that the robot has not entered this client. @kacperzuk-neti Can you help us restore the data to normal first? We need it now.

I've reported this to the data provider. I will update you when we have a fix.

**Comment by Filip-L** [comment]
@a1991car, the issue with the application on allocator.tech has been resolved, and you can use it again.

**Comment by Wennegit** [comment]
thanks.we checked.the sp support http. but spark is 0. can you help us to have a look？

<img width="1026" alt="Image" src="https://github.com/user-attachments/assets/4ed10e28-eeb9-4525-b83d-c7608bd8c823" />


https://cid.contact/providers 

![Image](https://github.com/user-attachments/assets/b8f650f9-d454-4d62-91c4-7ea27bd67b71)

**Comment by kacperzuk-neti** [comment]
@Wennegit Please try following this guide: https://docs.filspark.com/time-to-first-byte/troubleshooting-miner-score
If that doesn't help, please contact Spark team directly: https://docs.filspark.com/time-to-first-byte/troubleshooting-miner-score#block-423e33326ba048fdb04b197687bdf03e

**Comment by kacperzuk-neti** [comment]
Data provider solved the issue that was preventing bot from providing reports. If any other problems still remain, please open a new issue.
