### ISSUE TITLE
Datacap amount not updated after refresh of RKH

### ISSUE THREAD

**Issue by cryptowhizzard** [fidlabs/allocator-tooling#151]
Hello,

The amount of datacap that i see is not updated on my allocator pathways. This while the datacap seems allocated on chain.

See allocators remaining balance versus the 10 PB of datacap present.

<img width="1703" height="887" alt="Image" src="https://github.com/user-attachments/assets/3ac4156d-2386-4213-9708-e542600a6d5f" />
<img width="1998" height="789" alt="Image" src="https://github.com/user-attachments/assets/414328a4-6c9d-48a6-b9f8-d2831380645f" />

**Comment by Filip-L** [comment]
Thanks for the report. I'm investigating the problem

**Comment by Filip-L** [comment]
You entered the wrong allocation_bookkeeping URL during the refresh process. In your JSON file(https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/recb1FNn1Kmsk2N3p.json), there is only a link to your profile(https://github.com/cryptowhizzard), instead of a link to the repository.

Please create a change request to fix this. You can create a specific issue at https://github.com/filecoin-project/Allocator-Registry/issues.

<img width="1447" height="779" alt="Image" src="https://github.com/user-attachments/assets/1fc7941d-ec0e-456f-8021-8dc7c19cbf3f" />

**Comment by cryptowhizzard** [comment]
Thanks. Please see the issues created.

Apologies for the inconvenience.

**Comment by Filip-L** [comment]
In the issue, you referred to the old JSON files. The new JSON file where the problem occurs has "application_number": 860. The application with "application_number": 856, where the repo is `Fil-A-1`, has a valid `allocation_bookkeeping`, but it still has an incorrect GitHub handle, which should be fixed by creating a separate issue. 

<img width="1363" height="736" alt="Image" src="https://github.com/user-attachments/assets/6aee6466-0169-44d3-a6c2-db33e587b4fe" />

**Comment by cryptowhizzard** [comment]
See:

https://github.com/filecoin-project/Allocator-Registry/issues/1069
https://github.com/filecoin-project/Allocator-Registry/issues/1070

Thanks for the help. I hope this fixes it.

**Comment by cryptowhizzard** [comment]
I see this issue is closed , but things still do not work as expected.

One pathway is totally gone now ( Fil-A1 ) . Fil-A2 is still there , but the datacap is still at 512 TB

<img width="1274" height="359" alt="Image" src="https://github.com/user-attachments/assets/ea8ff772-7797-4412-8570-60b70357c687" />

**Comment by Filip-L** [comment]
@cryptowhizzard, I’ve closed the issue since all necessary steps have been completed from my side. Currently, we're waiting for updates on the JSON allocator files. Once those changes are implemented properly, everything should function as intended.

**Comment by Filip-L** [comment]
I saw on Slack that your issue has been resolved. I'm closing the ticket
